-- Migration 005: SPEI Add-on (Conekta integration)
-- Adds CLABE per contact and SPEI config per tenant

-- Each contact gets a unique CLABE generated via Conekta
ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS clabe               VARCHAR(18)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS conekta_customer_id TEXT         DEFAULT NULL;

-- Tenant-level SPEI configuration
ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS spei_addon_enabled  BOOLEAN      DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS payout_clabe        VARCHAR(18)  DEFAULT NULL;

-- Index for fast CLABE lookup on incoming Conekta webhooks
CREATE INDEX IF NOT EXISTS idx_contacts_conekta_customer_id
  ON contacts (conekta_customer_id)
  WHERE conekta_customer_id IS NOT NULL;

COMMENT ON COLUMN contacts.clabe IS
  'Unique 18-digit CLABE generated by Conekta for this contact. Used for SPEI payment reconciliation.';
COMMENT ON COLUMN contacts.conekta_customer_id IS
  'Conekta customer ID (cus_...) linked to this contact for recurring SPEI.';
COMMENT ON COLUMN tenants.spei_addon_enabled IS
  'When true, contacts get a unique CLABE and payment reminders include it.';
COMMENT ON COLUMN tenants.payout_clabe IS
  'CLABE of the tenant bank account where Conekta disperses collected payments.';
